### ISSUE TITLE
Clarification on the License

### ISSUE THREAD

**Issue by jeromeof** [java-json-tools/json-schema-validator#204] opened 2016-09-07 09:44 UTC
Hi,
  This project has a Dual license but I have a question as to whether its a LGPL or ASL (i.e. someone can pick either LGPL or ASL depending on their project needs) or that this project uses an 'And' license terms (i.e. the LGPL and ASL). 

Thanks

**Comment by toddobryan** [comment] 2017-02-08 19:26
Duplicate of #136

**Closed** 2019-09-05 11:16 UTC
